# Main Page Title
title: "Example Portfolio"

# Your name
name: "Igor Kowalczyk"

# Main section title
section: "Portfolio"

# Your job
work: "Front-End Developer"

# Section E-Mail link or anchor
section-email: "#contact"

# Description
description: "Igor Kowalczyk portfolio"

# Base url (Only dir eg. /blog | /portfolio)
baseurl: ""

# Link to the main page (or subpage)
url: "https://example.com"

# Contact E-Mail
email: "example@email.com"

# Your Wattpad account name
wattpad: "example"

# Arc.io key
arc: "arc-widget-key"

# Your Facebook account (with tag if you have)
facebook: igor-kowalczyk.0000
# facebook: 51144145433434332

# Your Instagram account name
instagram: example_name

# Your Discord account or server (link)
discord: "https://discord.gg/example"

# Github username
github_username: "example"

# Twitter username
twitter: "@example"

# Social Media section (boolean)
social-media:
 enabled: "true"

# Display svg decorations (boolean)
cards:
 enabled: "true"

# Extra link on navigation
blog: "/extra"
# Title of the extra link
blog-title: "Extra Link"

# Support to mobile browsers (Itâ€™s unknown what range of browsers support this meta tags) [Better to set the value to "false"!] (Boolean)
mobile: "false"

# First Launch of the site
first-launch: "2137"

# Timezone
timezone: "Europe/Warsaw"

# Encoding (default: utf-8)
encoding: utf-8

# Markdown and Default theme
markdown: kramdown
theme: minima

# Exlude files/folder
exclude:
 - Gemfile
 - Gemfile.lock

# Contact form
form:
 enabled: "true" # Boolean
 action: "https://example.com/form/post" # Form action, must support xhr requests
 img: "/lib/pics/special/email.svg" # Form additional image
 img-enabled: "false" # Display form additional image (boolean)

# Google Tracking ID
tracking_id: "UA-123456789-1"

# Google Site Verification ID
verification: "-qwertyuiopasdfghjklzxcvbnm"

# Coding stats
wakatime:
 enabled: "true" # Boolean
 started: "2137" # Year when wakatime started moritoring your code activity
 link: "https://wakatime.com/@cari-i-love-you" # Your wakatime profile link
 embed: "https://wakatime.com/share/@example/6dbf5beb-695a-40b1-9251-618ad59bca36.svg" # Coding stats embed image in .svg format
