name: Auto Format

on:
 workflow_dispatch:

jobs:
 format:
  name: âœ¨ Prettier format
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
     with:
      ref: ${{ github.head_ref }}
   - uses: actions/setup-node@v1
     with:
      node-version: "16.x"
   - name: ðŸ§± Prettier format
     run: |
      npm i prettier@2.6.2 --no-package-lock --no-save --legacy-peer-deps
      npm run format
   - name: ðŸ§± Formatting check
     run: npm run format:check
   - name: ðŸš€ Commit changes
     uses: stefanzweifel/git-auto-commit-action@v4
     with:
      commit_message: "[ðŸš€] Code formatting"
      branch: ${{ github.head_ref }}
      commit_user_name: IgorKowalczykBot
      commit_user_email: igor.kowalczyk.bot@onet.pl
